#!/usr/bin/env bash

#script used to extract and copy the files for the delaunay triangulation
# it must be called from the delaunay dir of geogram
#
# usage:
#
# myExtract Delaunay.psm tmp/path/delaunay
#

. $1

for i in ${HEADERS}
do
	DIR=`dirname $i`
	if [ ! -d "$DIRECTORY" ]; then
  		mkdir -p $2/${DIR}
	fi
	cp -rf $i $2/$i
done
for i in ${SOURCES}
do
	DIR=`dirname $i`
	if [ ! -d "$DIRECTORY" ]; then
  		mkdir -p $2/${DIR}
	fi
	cp -rf $i $2/$i
done